spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: ead-secret
  profiles:
    active: h2
