spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:'
    cloud:
      config:
        discovery:
          serviceId: ead-config-server
  profiles:
    active: h2
